### ISSUE TITLE
Submitting the PAP level of data is not possible

### ISSUE THREAD

**Issue by mback2k** [TheHive-Project/Cortex4py#21]
Since instead of passing the content of `observable` as `post`, the `post` dictionary is recreated only with the `dataType` and `tlp` level, it is currently not possible to submit the PAP level to the job:
https://github.com/TheHive-Project/Cortex4py/blob/629069aff0328a33bb0200e106ef436f50938632/cortex4py/controllers/analyzers.py#L49-L56

**Comment by mback2k** [comment]
Will be fixed once #18 is released.

**Comment by mback2k** [comment]
@nadouani Any ETA for a new release? I am currently using a monkey-patched version to fix this issue.

**Comment by nadouani** [comment]
Closing this issue using #18
