### ISSUE TITLE
Specifics of job.status and report['success']

### ISSUE THREAD

**Issue by geekscrapy** [TheHive-Project/Cortex4py#9]
Hi,

Can you give some clarification to the differences between job.status and report['success'] fields, please? In particular when job.status would indicate success but the report indicates unsuccessful.

TIA!

**Comment by nadouani** [comment]
A job might fail because of a reason related to the analyzer or because of any other issue in Cortex.

I think that the job is marked as failed when the analyzer `report.success` is false.

So I don't see any situation where job.status is success and report.status is error.
